Constant:
  coefficient:
    type: LogUniform
    lower_limit: 1.0e-06
    upper_limit: 1000000.0
    width_modifier:
      type: Relative
      value: 0.5
    gaussian_limits:
      lower: 0.0
      upper: inf
