EinsteinRadiusAXVLine:
  figure:
    c: b
    linestyle: --
  subplot:
    c: b
    linestyle: --
HalfLightRadiusAXVLine:
  figure:
    c: g
    linestyle: -.
  subplot:
    c: kg
    linestyle: -.
ModelFluxesYXScatter:
  figure:
    c: c
  subplot:
    c: c
