SMBHBinary:
  centre_0:
    type: Gaussian
    mean: 0.0
    sigma: 1.0
    lower_limit: -inf
    upper_limit: inf
    width_modifier:
      type: Absolute
      value: 0.05
    gaussian_limits:
      lower: -inf
      upper: inf
  centre_1:
    type: Gaussian
    mean: 0.0
    sigma: 1.0
    lower_limit: -inf
    upper_limit: inf
    width_modifier:
      type: Absolute
      value: 0.05
    gaussian_limits:
      lower: -inf
      upper: inf
  separation:
    type: Uniform
    lower_limit: 0.0
    upper_limit: 1.0
    width_modifier:
      type: Relative
      value: 0.25
    gaussian_limits:
      lower: 0.0
      upper: inf
  angle_binary:
    type: Uniform
    lower_limit: 0.0
    upper_limit: 360.0
    width_modifier:
      type: Relative
      value: 0.25
    gaussian_limits:
      lower: 0.0
      upper: inf
  mass:
    type: LogUniform
    lower_limit: 1000000.0
    upper_limit: 10000000000000.0
    width_modifier:
      type: Relative
      value: 0.25
    gaussian_limits:
      lower: 0.0
      upper: inf
  mass_ratio:
    type: Uniform
    lower_limit: 1.0
    upper_limit: 10.0
    width_modifier:
      type: Relative
      value: 0.25
    gaussian_limits:
      lower: 0.0
      upper: inf
  redshift_object:
    type: Uniform
    lower_limit: 0.0
    upper_limit: 1.0
    width_modifier:
      type: Relative
      value: 0.5
    gaussian_limits:
      lower: 0.0
      upper: inf
  redshift_source:
    type: Uniform
    lower_limit: 0.0
    upper_limit: 1.0
    width_modifier:
      type: Relative
      value: 0.5
    gaussian_limits:
      lower: 0.0
      upper: inf