SersicCore:
  alpha:
    type: Uniform
    lower_limit: 4.5
    upper_limit: 5.5
    width_modifier:
      type: Absolute
      value: 3.0
    gaussian_limits:
      lower: 4.5
      upper: 5.5
  centre_0:
    type: Gaussian
    mean: 0.0
    sigma: 0.3
    lower_limit: -inf
    upper_limit: inf
    width_modifier:
      type: Absolute
      value: 0.05
    gaussian_limits:
      lower: -inf
      upper: inf
  centre_1:
    type: Gaussian
    mean: 0.0
    sigma: 0.3
    lower_limit: -inf
    upper_limit: inf
    width_modifier:
      type: Absolute
      value: 0.05
    gaussian_limits:
      lower: -inf
      upper: inf
  effective_radius:
    type: Uniform
    lower_limit: 0.0
    upper_limit: 30.0
    width_modifier:
      type: Relative
      value: 1.0
    gaussian_limits:
      lower: 0.0
      upper: inf
  ell_comps_0:
    type: Gaussian
    mean: 0.0
    sigma: 0.3
    lower_limit: -1.0
    upper_limit: 1.0
    width_modifier:
      type: Absolute
      value: 0.2
    gaussian_limits:
      lower: -1.0
      upper: 1.0
  ell_comps_1:
    type: Gaussian
    mean: 0.0
    sigma: 0.3
    lower_limit: -1.0
    upper_limit: 1.0
    width_modifier:
      type: Absolute
      value: 0.2
    gaussian_limits:
      lower: '-1.0'
      upper: '1.0'
  gamma:
    type: Uniform
    lower_limit: 0.0
    upper_limit: 0.5
    width_modifier:
      type: Absolute
      value: 0.1
    gaussian_limits:
      lower: 0.0
      upper: inf
  radius_break:
    type: Uniform
    lower_limit: 0.0
    upper_limit: 10.0
    width_modifier:
      type: Absolute
      value: 0.1
    gaussian_limits:
      lower: 0.0
      upper: inf
  sersic_index:
    type: Uniform
    lower_limit: 0.8
    upper_limit: 5.0
    width_modifier:
      type: Absolute
      value: 1.5
    gaussian_limits:
      lower: 0.8
      upper: 5.0
SersicSphCore:
  alpha:
    type: Uniform
    lower_limit: 4.5
    upper_limit: 5.5
    width_modifier:
      type: Absolute
      value: 3.0
    gaussian_limits:
      lower: 4.5
      upper: 5.5
  centre_0:
    type: Gaussian
    mean: 0.0
    sigma: 0.3
    lower_limit: -inf
    upper_limit: inf
    width_modifier:
      type: Absolute
      value: 0.05
    gaussian_limits:
      lower: -inf
      upper: inf
  centre_1:
    type: Gaussian
    mean: 0.0
    sigma: 0.3
    lower_limit: -inf
    upper_limit: inf
    width_modifier:
      type: Absolute
      value: 0.05
    gaussian_limits:
      lower: -inf
      upper: inf
  effective_radius:
    type: Uniform
    lower_limit: 0.0
    upper_limit: 30.0
    width_modifier:
      type: Relative
      value: 1.0
    gaussian_limits:
      lower: 0.0
      upper: inf
  gamma:
    type: Uniform
    lower_limit: 0.0
    upper_limit: 0.5
    width_modifier:
      type: Absolute
      value: 0.1
    gaussian_limits:
      lower: 0.0
      upper: inf
  radius_break:
    type: Uniform
    lower_limit: 0.0
    upper_limit: 10.0
    width_modifier:
      type: Absolute
      value: 0.1
    gaussian_limits:
      lower: 0.0
      upper: inf
  sersic_index:
    type: Uniform
    lower_limit: 0.8
    upper_limit: 5.0
    width_modifier:
      type: Absolute
      value: 1.5
    gaussian_limits:
      lower: 0.8
      upper: 5.0
