gNFW:
  centre_0:
    type: Gaussian
    mean: 0.0
    sigma: 0.1
    lower_limit: -inf
    upper_limit: inf
    width_modifier:
      type: Absolute
      value: 0.05
    gaussian_limits:
      lower: -inf
      upper: inf
  centre_1:
    type: Gaussian
    mean: 0.0
    sigma: 0.1
    lower_limit: -inf
    upper_limit: inf
    width_modifier:
      type: Absolute
      value: 0.05
    gaussian_limits:
      lower: -inf
      upper: inf
  ell_comps_0:
    type: Gaussian
    mean: 0.0
    sigma: 0.3
    lower_limit: -1.0
    upper_limit: 1.0
    width_modifier:
      type: Absolute
      value: 0.2
    gaussian_limits:
      lower: -1.0
      upper: 1.0
  ell_comps_1:
    type: Gaussian
    mean: 0.0
    sigma: 0.3
    lower_limit: -1.0
    upper_limit: 1.0
    width_modifier:
      type: Absolute
      value: 0.2
    gaussian_limits:
      lower: -1.0
      upper: 1.0
  inner_slope:
    type: Uniform
    lower_limit: 0.0
    upper_limit: 2.0
    width_modifier:
      type: Absolute
      value: 0.3
    gaussian_limits:
      lower: -1.0
      upper: 3.0
  kappa_s:
    type: Uniform
    lower_limit: 0.0
    upper_limit: 1.0
    width_modifier:
      type: Relative
      value: 0.2
    gaussian_limits:
      lower: 0.0
      upper: inf
  scale_radius:
    type: Uniform
    lower_limit: 0.0
    upper_limit: 30.0
    width_modifier:
      type: Relative
      value: 0.2
    gaussian_limits:
      lower: 0.0
      upper: inf
gNFWSph:
  centre_0:
    type: Gaussian
    mean: 0.0
    sigma: 0.1
    lower_limit: -inf
    upper_limit: inf
    width_modifier:
      type: Absolute
      value: 0.05
    gaussian_limits:
      lower: -inf
      upper: inf
  centre_1:
    type: Gaussian
    mean: 0.0
    sigma: 0.1
    lower_limit: -inf
    upper_limit: inf
    width_modifier:
      type: Absolute
      value: 0.05
    gaussian_limits:
      lower: -inf
      upper: inf
  inner_slope:
    type: Uniform
    lower_limit: 0.0
    upper_limit: 2.0
    width_modifier:
      type: Absolute
      value: 0.3
    gaussian_limits:
      lower: -1.0
      upper: 3.0
  kappa_s:
    type: Uniform
    lower_limit: 0.0
    upper_limit: 1.0
    width_modifier:
      type: Relative
      value: 0.2
    gaussian_limits:
      lower: 0.0
      upper: inf
  scale_radius:
    type: Uniform
    lower_limit: 0.0
    upper_limit: 30.0
    width_modifier:
      type: Relative
      value: 0.2
    gaussian_limits:
      lower: 0.0
      upper: inf
