gNFWVirialMassConcSph:
  centre_0:
    type: Gaussian
    mean: 0.0
    sigma: 0.1
    lower_limit: -inf
    upper_limit: inf
    width_modifier:
      type: Absolute
      value: 0.05
    gaussian_limits:
      lower: -inf
      upper: inf
  centre_1:
    type: Gaussian
    mean: 0.0
    sigma: 0.1
    lower_limit: -inf
    upper_limit: inf
    width_modifier:
      type: Absolute
      value: 0.05
    gaussian_limits:
      lower: -inf
      upper: inf
  log10m_vir:
    type: Uniform
    lower_limit: 7.0
    upper_limit: 12.0
    width_modifier:
      type: Relative
      value: 0.5
    gaussian_limits:
      lower: 0.0
      upper: inf
  c_2:
    type: LogUniform
    lower_limit: 1.0
    upper_limit: 100.0
    width_modifier:
      type: Relative
      value: 0.5
    gaussian_limits:
      lower: 0.0
      upper: inf
  overdens:
    type: Uniform
    lower_limit: 100.0
    upper_limit: 250.0
    width_modifier:
      type: Relative
      value: 0.5
    gaussian_limits:
      lower: 0.0
      upper: inf
  redshift_object:
    type: Uniform
    lower_limit: 0.0
    upper_limit: 1.0
    width_modifier:
      type: Relative
      value: 0.5
    gaussian_limits:
      lower: 0.0
      upper: inf
  redshift_source:
    type: Uniform
    lower_limit: 0.0
    upper_limit: 1.0
    width_modifier:
      type: Relative
      value: 0.5
    gaussian_limits:
      lower: 0.0
      upper: inf
  inner_slope:
    type: Uniform
    lower_limit: 0.0
    upper_limit: 2.0
    width_modifier:
      type: Absolute
      value: 0.3
    gaussian_limits:
      lower: -1.0
      upper: 3.0