model.LambdaCDMWrap:
  H0:
    type: Constant
    value: 67.66
  Om0:
    type: Constant
    value: 0.30966
  Ode0:
    type: Constant
    value: 0.69034
  Tcmb0:
    type: Constant
    value: 2.7255
  Neff:
    type: Constant
    value: 3.046
  m_nu:
    type: Constant
    value: 0.06
  Ob0:
    type: Constant
    value: 0.04897
model.FlatLambdaCDMWrap:
  H0:
    type: Constant
    value: 67.66
  Om0:
    type: Constant
    value: 0.30966
  Tcmb0:
    type: Constant
    value: 2.7255
  Neff:
    type: Constant
    value: 3.046
  m_nu:
    type: Constant
    value: 0.06
  Ob0:
    type: Constant
    value: 0.04897
model.FlatwCDMWrap:
  H0:
    type: Constant
    value: 67.66
  Om0:
    type: Constant
    value: 0.30966
  w0:
    type: Constant
    value: -1.0
  Tcmb0:
    type: Constant
    value: 2.7255
  Neff:
    type: Constant
    value: 3.046
  m_nu:
    type: Constant
    value: 0.06
  Ob0:
    type: Constant
    value: 0.04897